### ISSUE TITLE
Replace C4Ro logo in footer

### ISSUE THREAD

**Issue by overeha** [code4romania/ckanext-dataportaltheme#106]
Replace the old logo with the new version in the website footer. 
New logo: https://code4.ro/images/logo-full.svg

**Comment by costibleotu** [comment]
@overeha the logo you provided has black text.
We need one with white text.
![image](https://user-images.githubusercontent.com/1089585/67665493-81284a00-f972-11e9-9aa9-d9fefa40ae64.png)
