### ISSUE TITLE
List of issues found during manual testing

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/ckanext-dataportaltheme#116]
Although many of these issues are probably already known to the developers, like for example a few related to content unavailability, I am attaching all my findings here for the record.
1.	**Data portal drop-down hidden behind sidebar content and does not redirect to other city:**
Context: Data portal drop-down shows the possibility to switch between cities.
Expected behavior: To be redirected to another city.
Actual behavior: No redirecting. Also, in “Seturi de date”, “Manage account info” and others sections, the bottom option “Data portal Constanta” is not visible, as it pops up behind the sidebar.
Issue: sidebar positioning to be changed.
2.	 **“Alte resurse” section unavailable**
Context: clicking “Alte resurse” button:
Expected behavior: to have visibility over “Alte resurse” content.
Actual behavior: “Alte resurse” button redirects to “Principii esentiale”.
Issue: Missing content/section.
3.	**Hyperlink missing in: (mai multe informații aici)**
Context: In “Despre” section, paragraph “Ce este Data Portal Timișoara” the contents in brackets: (mai multe informații aici).
Expected behavior: expected a hyperlink on “aici”.
Actual behavior: No hyperlink.
Issue: hyperlink required.
4.	**Forgot password with no ID**
Context: In Log in section, forgot your password for an inexistent ID.
Expected behavior: a message stating that “User not found”.
Actual behavior: message stating “matched several users”, although a random meaningless string was input.
Issue: add a “User not found” type of message.
5.	**Forgot password with actual ID throws error message** 
Context: In Log in section, forgot your password for an existent ID.
Expected behavior: to through the reset password process.
Actual behavior: error message stating: 
Could not send reset link: SMTP server could not be connected to: "localhost" [Errno 111] Connection refused
Issue: not able to recover/reset password.
6.	**“Despre” section sets language to English**
Context: Click “Despre” while in Romanian or Hungarian.
Expected behavior: Go to “Despre” in Romanian or Hungarian.
Actual behavior: Goes to the English version of “Despre”.
Issue: should go to “Despre” in the same language.
7.	**Social media buttons redirecting back to the same page**
Context: In all sections there are 4 social media buttons available (Facebook, Instagram, Linkedin and Twitter).
Expected behavior: Clicking the buttons opens the page’s social media page in a new tab.
Actual behavior: All buttons open up the same Data portal page. There is no connection to the social media pages.
Issue: link the buttons to the social media pages links.
8.	**Other languages not available**
Context: Change language from drop down list
Expected behavior: Change to English or Hungarian.
Actual behavior: Page only available in Romanian.
Issue: Page in English and Hungarian to be added.
9.	**“Verifica seturi de date” redirects to home page**
Context: Click “Verifica seturi de date”
Expected behavior: Go to “Verifica seturi de date” section.
Actual behavior: Redirects to home page.
Issue: go to actual section.
10.	**“Linkuri utile” not entirely available**
Context: checking each of the links
Expected behavior: Go to each link.
Actual behavior: 
- Termeni și condiții - empty
- Politica de confidențialitate – redirects back to About section
- Codul de conduită – appears twice: first entry links to About section
- Politica de cookie-uri – empty
- Codul de conduită second entry – links to a code of conduct
- Code 4 Romania – links to https://code4.ro/ro/ 
- Contact – opens an outlook email window
Issue: all links should go to their intended location.
11.	**Register -> full name containing digits permitted (minor impact)**
Context: In Register section, adding full name as digits only.
Expected behavior: an error due to only digits introduced.
Actual behavior: able to submit full name digits only (123 456)
Issue: check for letters within full name.

**Comment by surdu** [comment]
In addition to the clarifications bellow, I would suggest splitting this issues into multiple ones. I could do that.

Some clarifications required: 
1. First part was fixed in #117 . For the second part of the issue, please provide links / pattern for data portal in other cities. Pattern example would be `https://xx.dataportal.ro` where `xx` is the city code in lowercase.
2. Do we have UI mocks for "Alte resurse" page? Can't find it [here](https://www.figma.com/file/P60qSupJkefpT7K4rT5PQuva/Data-Portal-Cluj-Napoca?node-id=0%3A1)
3. Please provide hyperlink
