### ISSUE TITLE
Social media buttons redirecting back to the same page

### ISSUE THREAD

**Issue by catileptic** [code4romania/ckanext-dataportaltheme#127]
**Context**: In all sections there are 4 social media buttons available (Facebook, Instagram, Linkedin and Twitter).
**Expected behavior**: Clicking the buttons opens the page’s social media page in a new tab.
**Actual behavior**: All buttons open up the same Data portal page. There is no connection to the social media pages.
**Issue**: link the buttons to the social media pages links.

**Comment by surdu** [comment]
@catileptic Those URL are [configurable here](https://test.dataportal.ro/ckan-admin/dataportal). I've changed them for now to point to the root of their respective applications.
