### ISSUE TITLE
Dynamic social bar

### ISSUE THREAD

**Issue by boldisteanu** [code4romania/ckanext-dataportaltheme#25]
Depends on [#24](https://github.com/code4romania/ckanext-dataportaltheme/issues/24)

- [x] define in the configuration all the profile links for the social accounts
- [x] if the social account is not defined, hide the logo
- [x] links should open in new tabs

**Comment by surdu** [comment]
Please note that usually the sharing widgets open in pop-ups

**Comment by mihaela94** [comment]
Iau eu asta
