### ISSUE TITLE
Provision Vagrant with real data and accounts

### ISSUE THREAD

**Issue by costibleotu** [code4romania/ckanext-dataportaltheme#27]
- [x]  Add categories with icons
- [x] Add 2 datasets (regular data to plot & map)
- [x] Create Code4 Organization
- [x] Create demo user in Code4 Organization
- [x] Install Datapusher in Vagrant
- [x] Create dump
- [x] Restore Vagrant from dump
- [x] Make sure Solr is running  
- [x] Write Documentation

**Comment by ancaspatariu** [comment]
Small issue: "Cultura"  (new category nor present in the prototype) has the same icon as  "Educatie". Can we make a note somewhere to replace that in the future if the category remains?

**Comment by costibleotu** [comment]
I know. I will make an issue for @overeha 
Chris Torch mentioned (and he was right) after our presentation, that we miss the "Culture" group :)
