### ISSUE TITLE
Create data visualization layout

### ISSUE THREAD

**Issue by surdu** [code4romania/ckanext-dataportaltheme#35]
Data visualization page has 2 columns: 
 - the main section, containing the visualization types (Grafic, Tabelar & Harta) switcher, the visualization itself and the additional information tables.
- the secondary section containing download button, search and filter the data, data sharing section and similar data sets section

For all the charts below we'll use placeholder images for now.

Please note below the screenshots for graphic and tabular views and [prototypes can be found here](https://www.figma.com/proto/vnziJOneB0PTE3cJy54B6e/Data-Portal-Timi%C8%99oara?node-id=101%3A48&scaling=min-zoom).

![vizualizare set de date](https://user-images.githubusercontent.com/11520795/52906557-19ecbe80-3257-11e9-806c-09ace19d663f.png)
![vizualizare set de date - tabelar](https://user-images.githubusercontent.com/11520795/52906561-22dd9000-3257-11e9-953d-e26b059f5c70.png)

**Comment by ancaspatariu** [comment]
This issue was split into multiple smaller issues.
