### ISSUE TITLE
Create color palette for file formats

### ISSUE THREAD

**Issue by ancaspatariu** [code4romania/ckanext-dataportaltheme#44]
Different file formats will have different color coded labels (see attached example for CSV).

We need to create a color palette for the most popular data formats (and a fallback color for all others)

Here's a good starting point list (even though it):
- CSV - ```rgba(39, 174, 96, 0.6)```
- XML - ...
- JSON - ...
- HTML - ...
- XLS - ...
- PDF - ...
- RSS - ...
- TXT - ...
- XMS - ...

**Comment by surdu** [comment]
@overeha Should we proceed with the colors mentioned above?
