### ISSUE TITLE
Create Footer for Data Portal

### ISSUE THREAD

**Issue by overeha** [code4romania/ckanext-dataportaltheme#55]
The Footer will consist of three areas: 

**Area 1: ** 
- newsletter subscription area
- standard Code for Romania copyright section (phrase and logo)
**Area 2:** 
- Data Portal logo
**Area 3**
- useful links directing to the Data Portal project (main website), Terms and conditions, Cookie Policy, Code of Conduct, Code for Romania homepage and a Contact link (mailto: contact@code4.ro)

Example like in wireframe here:
![noutati](https://user-images.githubusercontent.com/45068169/51713950-53595200-203c-11e9-9f40-0c7a6e6128d3.png)

**Styles:** 
- background: Black 
- font: Titilium Web, white
- logos:
![data portal 1](https://user-images.githubusercontent.com/45068169/51706683-e6d45800-2027-11e9-8e1b-70d605acf8e2.png)

![code4_logo_transparency_white](https://user-images.githubusercontent.com/45068169/51706817-3c106980-2028-11e9-80fa-945bf5c5a553.png)

**Comment by surdu** [comment]
@costibleotu I've addressed you last checklist in https://github.com/code4romania/ckanext-dataportaltheme/pull/76
