### ISSUE TITLE
Create a python script that imports data from a JSON/XML feed

### ISSUE THREAD

**Issue by costibleotu** [code4romania/ckanext-dataportaltheme#95]
The City Halls will provide the data we will import in feeds (ex: http://data.e-primariaclujnapoca.ro/spargeri.json).

We need a script that that receives the following parameters:
* feed url
* Dataset token ( from DataPortal) 
* Dataset URI

The script should only insert the new entries, or update existing ones

**Comment by ovidiub13** [comment]
Salutare, aș dori și eu să mă implic în Code4Ro, și acest tichet pare o treabă numai bună să încep.

M-ați putea ghida unde să mă uit să aflu ce trebuie acest script să facă cu datele importate?

**Comment by costibleotu** [comment]
Salut!

Am facut chiar saptamana asta task-ul. Pana la urma am creat un [proiect separat](https://github.com/code4romania/dataportal-scheduler/blob/master/scheduler/app/tasks.py) care va avea rolul de a sincroniza feed-urile de date de la Primarii cu DataPortal  .

Momentan sunt aproape gata cu customizarea instantei de CKAN, si focusul principal acum e pe auditarea feed-urilor existente din primarii, si obtinerea de feeduri noi.

[Aici](https://test.dataportal.ro/) poti sa vezi ultima versiune a portalului (este in development)
